# Generated by Django 3.0.3 on 2020-02-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200228_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articel_text',
            new_name='article_text',
        ),
    ]
