# Generated by Django 3.0.3 on 2020-03-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_article_descriprion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_descriprion',
            new_name='article_description',
        ),
    ]
